a= int (input(" enter the number"))
b= int (input(" enter the number"))
c= int (input(" enter the number"))
d= int (input(" enter the number"))
e= int (input(" enter the number"))
f= int (input(" enter the number"))
g= int (input(" enter the number"))
h= int (input(" enter the number"))
s={a,b,c,d,e,f,g,h}
print(s)
